logging:
  level:
    org.springframework.r2dbc.core: debug
vote:
  expire:
    use-expire: true
  validation:
    item:
      use-validator: true
      regex-string: "[0-2]{2}"
    user-id:
      use-validator: true
      regex-string: "[a-zA-Z]+"
